services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MARIADB_SSL: "OFF" 
    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

  php-applikation:
    build: .
    container_name: php-applikation
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  db_data:
